### ISSUE TITLE
authentication: support alternative server for git and git-forge API (src.fp.o)

### ISSUE THREAD

**Issue by TomasTomecek** [packit/ogr#551]
This is gonna be a fun one: I tried to use upsint to create a PR in src.fedoraproject.org/rpms but failed because there are two different servers for the forge API and a git server:

I use SSH:
```
ssh://ttomecek@pkgs.fedoraproject.org/rpms/python-ogr.git
```

But pagure API is at
```
https://src.fedoraproject.org/rpms/python-ogr.git
```

I'm wondering if it's possible to set up an authentication entry which would recognize pkgs.fp.o but route API requests to src.fp.o. Tried these but none of them worked with SSH:
```
  fedora-dist-git:
    type: pagure
    instance_url: "https://src.fedoraproject.org/"
    token: ...
  fedora-dist-git2:
    type: pagure
    instance_url: "https://pkgs.fedoraproject.org/"
    token: ...
```

Worst case I could hard-code the logic to upsint though I think it would be useful to have in ogr itself.
